FROM nginx

WORKDIR /usr/src/app/

COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf.temp

COPY ./dist  /usr/share/nginx/html/

EXPOSE 80

CMD envsubst '$SERVER_URL'  < /etc/nginx/conf.d/default.conf.temp | envsubst '$AUTH_URL'  > /etc/nginx/conf.d/default.conf ; nginx -g 'daemon off;'